Add friends likes
Lilyziz/java-filmorate pull request #6
Opened 2023-05-13 22:31 UTC by Lilyziz

2023-05-14 14:55 UTC, utausheva reviewed
Привет!
Есть некоторые комментарии к распределению кода по уровням, разобравшись с которыми, ты точно поймешь, какой уровень за что отвечает))
Жду на следующей итерации)

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/IFilmStorage.java
> +    //void update(Film updatingFilm, Film film);
старый код нужно удалять перед отправкой на проверку

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getDescription().length() > 200) {
Валидация не должна быть на уровне хранилища, это бизнес-логика, которая должна быть либо в сервисе, либо в контроллере (на твой выбор).
Вообще в хранилище должны быть лишь простые CRUD операции, не стоит их усложнять расчетами.

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!film.getReleaseDate().isBefore(LocalDate.of(1985, 12, 28))) {
тоже валидация

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +
валидацию вынести на уровень выше

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public String userGiveLikeToFilm(@PathVariable long id, @PathVariable long userId) {
контроллеру не нужны строки с каким-то текстом)))
Либо ResponseEntity, либо объект, либо список данных, либо ничего)

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public String userGiveLikeToFilm(@PathVariable long id, @PathVariable long userId) {
это относится ко всем методам

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static long id = 0;
Генерация ид должна происходить на уровне хранилища, это его работа. Если ты будешь использовать хранилище, в котором ключами будут не long-числа, а строки, например, или картинки, как ты синхронизуешь сервис с этим хранилищем?

2023-05-14 14:55 UTC, utausheva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setId(generateId());
засеттить в сущность ид - работа хранилища

2023-05-19 18:56 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Collection<Film> getAllFilms() {
Более широко распространен интерфейс `List`, возвращай его вместо `Collection`

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("Get film with id " + id);
В логере мы по особенному передаем параметры, через шаблон: `{}`, вот так:

`log.info("Get film by id: {}", id);`

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Collection<Film> getTopFilmsWithCount(@RequestParam(value = "count",required = false, defaultValue = "10") long count) {
Строка вышла за допустимые 120 символов, нужно сделать перенос...

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        log.info("Users " + userService.getUserById(id).getLogin() + " and "
Кроме этого - не удобно же вот так складывать строки.
Вот так, куда приятнее выглядит

```
        log.info("Users {} and {} are friends now",
                 userService.getUserById(id).getLogin(),
                 userService.getUserById(friendId).getLogin());
```

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/IdException.java
> +public class IdException extends RuntimeException {
Не нужно быть настолько конкретным в названии исключения.
Пусть название отразит тот ответ который получит клиент, в данном случае: `HttpStatus.NOT_FOUND`.
Назови класс: `NotFoundException`, а в тексте сообщения отрази что не найдено и по какому полю искали.

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/InternalServerError.java
> +public class InternalServerError extends RuntimeException {
Не используется - можно удалить...

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
`ValidationException -> BadRequestException`

Код ошибки порождаемый этим исключением - `HttpStatus.BAD_REQUEST`

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(IFilmStorage filmStorage, UserService userService) {
Остался не нужным `UserService userService`

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.contains(film.getId())) {
В следующей работе я покажу тебе как пользоваться `Optional` и мы попробуем написать код в функциональном стиле, а пока оставим тут всё как есть...

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        Collection<Film> allFilms = getAllFilms().stream()
Ничего не мешает тебе сразу возвращать, без объявления переменной.
Обрати внимание на это и в других местах!

```
    @Override
    public Collection<Film> topFilmsWithCount(long count) {
        return getAllFilms().stream()
                            .sorted(Comparator.comparing(film -> -film.getLikes().size()))
                            .limit(count)
                            .collect(Collectors.toList());
    }
```

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        throw new IdException("There is no user with this id");
Проверки и бросание подобных исключений должны быть в сервисе.
Тут просто обновление.

Ведь уже в следующей работе у вас будет база данных, и тут будут только SQL запросы.

2023-05-19 18:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    private boolean descriptionValidator(String description) throws ValidationException {
Формально ты не корректно называешь методы... по конвенции методы это глаголы.
Но к тому же ты не используешь нигде возвращаемого значения.

В общем если твой метод генерит исключение то лучше метод так и назвать: 
`void throwIfDescriptionInvalid()`

2023-05-20 08:52 UTC, FanaticFiz approved these changes

2023-05-24 19:33 UTC, merged